from amazingmodels.network import Network
from amazingmodels.fcn import FCN
from amazingmodels.pspnet import PSPNet
from amazingmodels.segnet import SegNet
from amazingmodels.unet import UNet
from amazingmodels.pan import PAN
from amazingmodels.deeplab_v3 import DeepLabV3
from amazingmodels.deeplab_v3_plus import DeepLabV3Plus
from amazingmodels.refinenet import RefineNet
from amazingmodels.denseaspp import DenseASPP
from amazingmodels.bisegnet import BiSegNet
